label = "openmx"
structure = "POSCAR"
scf_criterion = 1e-8

xc = 'PBE'
eigensolver = 'Band'
scf_kgrid = [9, 9, 9]
scf_maxiter = 1000

spinpol = 'on'
smearing = 300


scf.restart = true
scf.Mixing.History = 20
scf.Mixing.StartPulay = 10

scf.Max.Mixing.Weight = 0.2


# initial magnetic moments for collinear 
[magnetic_moments]
magmom = [2.0, 2.0, 2.0, -3.0, -3.0, -3.5]

